name: Release update
on:
    workflow_dispatch:
jobs:
    release_update:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: zulu
            -   run: |
                    chmod +x gradlew
                    ./gradlew publish
