name: Release update
on:
    workflow_dispatch:
jobs:
    release_update:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: zulu
            -   run: |
                    chmod +x gradlew
                    ./gradlew publish
                env:
                    ORG_GRADLE_PROJECT_mavenUsername: ${{ secrets.MAVEN_USERNAME }}
                    ORG_GRADLE_PROJECT_mavenPassword: ${{ secrets.MAVEN_PASSWORD }}
                    ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
                    ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
